# test_data.py
"""
Test data for comprehensive model testing
Save your 13 test cases here in this format
"""

# Test data - 13 cases for model validation
TEST_DATA = [
    {
        'project_prf_year_of_project': 2006,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Financial transaction process/accounting',
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': 'MF',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'COBOL',
        'project_prf_functional_size': 60,
        'functional_size_group': 'S:<100',
        'project_prf_relative_size': 'S',
        'project_prf_normalised_work_effort': 3730,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 8,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 3,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2009,
        'external_eef_industry_sector': 'Financial',
        'external_eef_organisation_type': 'Financial, Property & Business Services',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Financial transaction process/accounting',
        'project_prf_development_type': 'Enhancement',
        'tech_tf_development_platform': 'MF',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'PL/I',
        'project_prf_functional_size': 90,
        'functional_size_group': 'S:<100',
        'project_prf_relative_size': 'S',
        'project_prf_normalised_work_effort': 5831,
        'project_prf_team_size_group': '5-8',
        'project_prf_max_team_size': 12,
        'project_prf_case_tool_used': 'No',
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 13,
        'tech_tf_architecture': 'Stand alone',
        'tech_tf_client_server': 'No',
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': 'Yes',
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': 2,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2012,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Business Application',
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': None,
        'tech_tf_language_type': '4GL',
        'tech_tf_primary_programming_language': None,
        'project_prf_functional_size': 63,
        'functional_size_group': 'S:<100',
        'project_prf_relative_size': 'S',
        'project_prf_normalised_work_effort': 1784,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 4,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 2,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2006,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Financial transaction process/accounting',
        'project_prf_development_type': 'Enhancement',
        'tech_tf_development_platform': 'MF',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'COBOL',
        'project_prf_functional_size': 143,
        'functional_size_group': 'M:100-999',
        'project_prf_relative_size': 'M1',
        'project_prf_normalised_work_effort': 9566,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 15,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 3,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2007,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Financial transaction process/accounting',
        'project_prf_development_type': 'Enhancement',
        'tech_tf_development_platform': 'PC',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'Visual Basic',
        'project_prf_functional_size': 577,
        'functional_size_group': 'M:100-999',
        'project_prf_relative_size': 'M2',
        'project_prf_normalised_work_effort': 9382,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 12,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 3,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2009,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Financial transaction process/accounting',
        'project_prf_development_type': 'Enhancement',
        'tech_tf_development_platform': 'MF',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'COBOL',
        'project_prf_functional_size': 271,
        'functional_size_group': 'M:100-999',
        'project_prf_relative_size': 'M1',
        'project_prf_normalised_work_effort': 2613,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 5,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 3,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2011,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Business Application',
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': None,
        'tech_tf_language_type': '4GL',
        'tech_tf_primary_programming_language': 'Visual Basic',
        'project_prf_functional_size': 160,
        'functional_size_group': 'M:100-999',
        'project_prf_relative_size': 'M1',
        'project_prf_normalised_work_effort': 989,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 4,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 2,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2013,
        'external_eef_industry_sector': 'Financial',
        'external_eef_organisation_type': 'Financial, Property & Business Services',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Business Application',
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': None,
        'tech_tf_language_type': '4GL',
        'tech_tf_primary_programming_language': 'Oracle',
        'project_prf_functional_size': 336,
        'functional_size_group': 'M:100-999',
        'project_prf_relative_size': 'M2',
        'project_prf_normalised_work_effort': 3494,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 6,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 2,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2014,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Business Application',
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': None,
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'Java',
        'project_prf_functional_size': 958,
        'functional_size_group': 'M:100-999',
        'project_prf_relative_size': 'M2',
        'project_prf_normalised_work_effort': 13200,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 12,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 2,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2006,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Financial transaction process/accounting',
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': 'PC',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'Java',
        'project_prf_functional_size': 1006,
        'functional_size_group': 'L:1000-2999',
        'project_prf_relative_size': 'L',
        'project_prf_normalised_work_effort': 23429,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 15,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 3,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': 'Web',
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2013,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Mobile Application',
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': 'PC',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'iOS',
        'project_prf_functional_size': 1244,
        'functional_size_group': 'L:1000-2999',
        'project_prf_relative_size': 'L',
        'project_prf_normalised_work_effort': 5773,
        'project_prf_team_size_group': '5-8',
        'project_prf_max_team_size': 6,
        'project_prf_case_tool_used': 'No',
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 3,
        'tech_tf_architecture': 'Client server',
        'tech_tf_client_server': 'Yes',
        'tech_tf_client_roles': 'mobile app',
        'tech_tf_server_roles': 'back-end',
        'tech_tf_type_of_server': 'back-end',
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2009,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': 'Business Application',
        'project_prf_application_type': 'Financial transaction process/accounting',
        'project_prf_development_type': 'Enhancement',
        'tech_tf_development_platform': 'MF',
        'tech_tf_language_type': '3GL',
        'tech_tf_primary_programming_language': 'COBOL',
        'project_prf_functional_size': 1252,
        'functional_size_group': 'L:1000-2999',
        'project_prf_relative_size': 'L',
        'project_prf_normalised_work_effort': 14437,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 10,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 3,
        'tech_tf_architecture': None,
        'tech_tf_client_server': None,
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    },
    {
        'project_prf_year_of_project': 2010,
        'external_eef_industry_sector': 'Banking',
        'external_eef_organisation_type': 'Banking',
        'project_prf_application_group': None,
        'project_prf_application_type': None,
        'project_prf_development_type': 'New Development',
        'tech_tf_development_platform': 'Multi',
        'tech_tf_language_type': '4GL',
        'tech_tf_primary_programming_language': '.Net',
        'project_prf_functional_size': 5667,
        'functional_size_group': 'XL:3000-8999',
        'project_prf_relative_size': 'XL',
        'project_prf_normalised_work_effort': 50457,
        'project_prf_team_size_group': None,
        'project_prf_max_team_size': 18,
        'project_prf_case_tool_used': None,
        'process_pmf_development_methodologies': 'Agile Development',
        'process_pmf_prototyping_used': None,
        'process_pmf_docs': 2,
        'tech_tf_architecture': 'Client server',
        'tech_tf_client_server': 'Yes',
        'tech_tf_client_roles': None,
        'tech_tf_server_roles': None,
        'tech_tf_type_of_server': None,
        'tech_tf_clientserver_description': None,
        'tech_tf_web_development': None,
        'tech_tf_dbms_used': None,
        'tech_tf_tools_used': None,
        'people_prf_project_user_involvement': None,
        'people_prf_project_manage_changes': None,
        'people_prf_personnel_changes': 0
    }
]

# Alternative: You can also load from CSV if you prefer
def load_test_data_from_csv(csv_file_path):
    """
    Load test data from CSV file
    CSV should have columns matching the dictionary keys above
    """
    try:
        import pandas as pd
        df = pd.read_csv(csv_file_path)
        # Convert DataFrame to list of dictionaries
        return df.to_dict('records')
    except Exception as e:
        print(f"Error loading CSV: {e}")
        return []

# Alternative: Load from JSON file
def load_test_data_from_json(json_file_path):
    """
    Load test data from JSON file
    JSON should be an array of objects with the same structure
    """
    try:
        import json
        with open(json_file_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading JSON: {e}")
        return []